//
// Created by e22-watson on 16/10/2019.
//
#pragma once
#ifndef BASIC_REB0RN_GAME_EVEYNULL_RETURNACTION_H
#  define BASIC_REB0RN_GAME_EVEYNULL_RETURNACTION_H

#endif // BASIC_REB0RN_GAME_EVEYNULL_RETURNACTION_H

enum ReturnAction
{
  NULL_ACTION = -1,
  GET_ITEM_DESCRIPTION = 0,
  PICK_UP_ITEM = 1,
  DROP_ITEM = 2,
  SET_FLAG_TRUE = 3,
  CHANGE_OBJECT_STATE = 4,
  CHANGE_OBJECT_NAME = 5,
  MOVE_ITEM_TO_LOCATION = 6,
  REMOVE_ITEM_FROM_LOCATION = 7,
  ADD_ROUTE_TO_LOCATION = 8
};